accueil:
    path: /
    defaults: { _controller: AppBundle:Default:index }

administration:
    path: /admin
    defaults: { _controller: AppBundle:Default:administration }
    
connexion:
    path: /connexion
    defaults: { _controller: AppBundle:User:connexion }

deconnexion:
   path: /deconnexion
   defaults: { _controller: AppBundle:User:deconnexion }

redirection_accueil:
    path: /redirection
    defaults: { _controller: AppBundle:User:redirect }

# Routes pour les requêtes AJAX
ajax_recherche_auteur:
    path: /ajax/recherche/auteur/{prenom}/{nom}
    defaults: { _controller: AppBundle:Ajax:rechercheAuteur }
    
ajax_recherche_periodique:
    path: /ajax/recherche/periodique/{nom}
    defaults: { _controller: AppBundle:Ajax:recherchePeriodique }
